name: stream_core
description: "Internal sdk with low-level utilities for the stream SDKs"
version: 0.0.1
repository: https://github.com/GetStream/stream-core-flutter
publish_to: none # Delete when ready to publish

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
