name: stream_core
description: "Internal sdk with low-level utilities for the stream SDKs"
version: 0.0.1
repository: https://github.com/GetStream/stream-core-flutter
publish_to: none # Delete when ready to publish

environment:
  sdk: ^3.6.2

dependencies:
  equatable: ^2.0.7
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  test: ^1.26.2
