name: stream_core
description: "Internal sdk with low-level utilities for the stream SDKs"
version: 0.0.1
repository: https://github.com/GetStream/stream-core-flutter
publish_to: none # Delete when ready to publish

environment:
  sdk: ^3.6.2

dependencies:
  collection: ^1.19.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  intl: ^0.20.2
  jose: ^0.3.4
  json_annotation: ^4.9.0
  meta: ^1.15.0
  rxdart: ^0.28.0
  web: ^1.1.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.26.2
