// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * ThumbnailFormat:
 * STREAM_THUMBNAIL_THUMBNAIL_FORMAT_JPEG:
 * STREAM_THUMBNAIL_THUMBNAIL_FORMAT_PNG:
 * STREAM_THUMBNAIL_THUMBNAIL_FORMAT_WEBP:
 *
 * Wire representation of the image format for a generated thumbnail.
 */
typedef enum {
  STREAM_THUMBNAIL_THUMBNAIL_FORMAT_JPEG = 0,
  STREAM_THUMBNAIL_THUMBNAIL_FORMAT_PNG = 1,
  STREAM_THUMBNAIL_THUMBNAIL_FORMAT_WEBP = 2
} ThumbnailFormat;

/**
 * ThumbnailRequest:
 *
 * A single thumbnail generation request sent to the native platform.
 */

G_DECLARE_FINAL_TYPE(ThumbnailRequest, thumbnail_request, , THUMBNAIL_REQUEST, GObject)

/**
 * thumbnail_request_new:
 * video: field in this object.
 * headers: field in this object.
 * thumbnail_path: field in this object.
 * format: field in this object.
 * max_height: field in this object.
 * max_width: field in this object.
 * time_ms: field in this object.
 * quality: field in this object.
 *
 * Creates a new #ThumbnailRequest object.
 *
 * Returns: a new #ThumbnailRequest
 */
ThumbnailRequest* thumbnail_request_new(const gchar* video, FlValue* headers, const gchar* thumbnail_path, ThumbnailFormat format, int64_t max_height, int64_t max_width, int64_t time_ms, int64_t quality);

/**
 * thumbnail_request_get_video
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the video field of @object.
 *
 * Returns: the field value.
 */
const gchar* thumbnail_request_get_video(ThumbnailRequest* object);

/**
 * thumbnail_request_get_headers
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the headers field of @object.
 *
 * Returns: the field value.
 */
FlValue* thumbnail_request_get_headers(ThumbnailRequest* object);

/**
 * thumbnail_request_get_thumbnail_path
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the thumbnailPath field of @object.
 *
 * Returns: the field value.
 */
const gchar* thumbnail_request_get_thumbnail_path(ThumbnailRequest* object);

/**
 * thumbnail_request_get_format
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the format field of @object.
 *
 * Returns: the field value.
 */
ThumbnailFormat thumbnail_request_get_format(ThumbnailRequest* object);

/**
 * thumbnail_request_get_max_height
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the maxHeight field of @object.
 *
 * Returns: the field value.
 */
int64_t thumbnail_request_get_max_height(ThumbnailRequest* object);

/**
 * thumbnail_request_get_max_width
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the maxWidth field of @object.
 *
 * Returns: the field value.
 */
int64_t thumbnail_request_get_max_width(ThumbnailRequest* object);

/**
 * thumbnail_request_get_time_ms
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the timeMs field of @object.
 *
 * Returns: the field value.
 */
int64_t thumbnail_request_get_time_ms(ThumbnailRequest* object);

/**
 * thumbnail_request_get_quality
 * @object: a #ThumbnailRequest.
 *
 * Gets the value of the quality field of @object.
 *
 * Returns: the field value.
 */
int64_t thumbnail_request_get_quality(ThumbnailRequest* object);

/**
 * thumbnail_request_equals:
 * @a: a #ThumbnailRequest.
 * @b: another #ThumbnailRequest.
 *
 * Checks if two #ThumbnailRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean thumbnail_request_equals(ThumbnailRequest* a, ThumbnailRequest* b);

/**
 * thumbnail_request_hash:
 * @object: a #ThumbnailRequest.
 *
 * Calculates a hash code for a #ThumbnailRequest object.
 *
 * Returns: the hash code.
 */
guint thumbnail_request_hash(ThumbnailRequest* object);

/**
 * thumbnail_request_to_string:
 * @object: a #ThumbnailRequest.
 *
 * Returns a string representation of a #ThumbnailRequest object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* thumbnail_request_to_string(ThumbnailRequest* object);

G_DECLARE_FINAL_TYPE(MessageCodec, message_codec, , MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int thumbnail_format_type_id;
extern const int thumbnail_request_type_id;

G_DECLARE_FINAL_TYPE(StreamThumbnailHostApi, stream_thumbnail_host_api, , STREAM_THUMBNAIL_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(StreamThumbnailHostApiResponseHandle, stream_thumbnail_host_api_response_handle, , STREAM_THUMBNAIL_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * StreamThumbnailHostApiVTable:
 *
 * Table of functions exposed by StreamThumbnailHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*thumbnail_data)(ThumbnailRequest* request, StreamThumbnailHostApiResponseHandle* response_handle, gpointer user_data);
  void (*thumbnail_file)(ThumbnailRequest* request, StreamThumbnailHostApiResponseHandle* response_handle, gpointer user_data);
} StreamThumbnailHostApiVTable;

/**
 * stream_thumbnail_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the StreamThumbnailHostApi API.
 */
void stream_thumbnail_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const StreamThumbnailHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * stream_thumbnail_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the StreamThumbnailHostApi API.
 */
void stream_thumbnail_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * stream_thumbnail_host_api_respond_thumbnail_data:
 * @response_handle: a #StreamThumbnailHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 * @return_value_length: (allow-none): location to write length of @return_value or %NULL to ignore.
 *
 * Responds to StreamThumbnailHostApi.thumbnailData. 
 */
void stream_thumbnail_host_api_respond_thumbnail_data(StreamThumbnailHostApiResponseHandle* response_handle, const uint8_t* return_value, size_t return_value_length);

/**
 * stream_thumbnail_host_api_respond_error_thumbnail_data:
 * @response_handle: a #StreamThumbnailHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to StreamThumbnailHostApi.thumbnailData. 
 */
void stream_thumbnail_host_api_respond_error_thumbnail_data(StreamThumbnailHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * stream_thumbnail_host_api_respond_thumbnail_file:
 * @response_handle: a #StreamThumbnailHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to StreamThumbnailHostApi.thumbnailFile. 
 */
void stream_thumbnail_host_api_respond_thumbnail_file(StreamThumbnailHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * stream_thumbnail_host_api_respond_error_thumbnail_file:
 * @response_handle: a #StreamThumbnailHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to StreamThumbnailHostApi.thumbnailFile. 
 */
void stream_thumbnail_host_api_respond_error_thumbnail_file(StreamThumbnailHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
