// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include <cmath>

#include <string.h>
#include "messages.g.h"
static guint G_GNUC_UNUSED flpigeon_hash_double(double v) {
  if (std::isnan(v)) {
    return static_cast<guint>(0x7FF80000);
  }
  if (v == 0.0) {
    v = 0.0;
  }
  union { double d; uint64_t u; } u;
  u.d = v;
  return static_cast<guint>(u.u ^ (u.u >> 32));
}
static gboolean G_GNUC_UNUSED flpigeon_equals_double(double a, double b) {
  return (a == b) || (std::isnan(a) && std::isnan(b));
}
static gboolean G_GNUC_UNUSED flpigeon_deep_equals(FlValue* a, FlValue* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (fl_value_get_type(a) != fl_value_get_type(b)) {
    return FALSE;
  }
  switch (fl_value_get_type(a)) {
    case FL_VALUE_TYPE_NULL:
      return TRUE;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(a) == fl_value_get_bool(b);
    case FL_VALUE_TYPE_INT:
      return fl_value_get_int(a) == fl_value_get_int(b);
    case FL_VALUE_TYPE_FLOAT: {
      return flpigeon_equals_double(fl_value_get_float(a), fl_value_get_float(b));
    }
    case FL_VALUE_TYPE_STRING:
      return g_strcmp0(fl_value_get_string(a), fl_value_get_string(b)) == 0;
    case FL_VALUE_TYPE_UINT8_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_uint8_list(a), fl_value_get_uint8_list(b), fl_value_get_length(a)) == 0;
    case FL_VALUE_TYPE_INT32_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int32_list(a), fl_value_get_int32_list(b), fl_value_get_length(a) * sizeof(int32_t)) == 0;
    case FL_VALUE_TYPE_INT64_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int64_list(a), fl_value_get_int64_list(b), fl_value_get_length(a) * sizeof(int64_t)) == 0;
    case FL_VALUE_TYPE_FLOAT_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      const double* a_data = fl_value_get_float_list(a);
      const double* b_data = fl_value_get_float_list(b);
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_equals_double(a_data[i], b_data[i])) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_deep_equals(fl_value_get_list_value(a, i), fl_value_get_list_value(b, i))) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_MAP: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      FlValue* key = fl_value_get_map_key(a, i);
      FlValue* val = fl_value_get_map_value(a, i);
      gboolean found = FALSE;
      for (size_t j = 0; j < len; j++) {
        FlValue* b_key = fl_value_get_map_key(b, j);
        if (flpigeon_deep_equals(key, b_key)) {
          FlValue* b_val = fl_value_get_map_value(b, j);
          if (flpigeon_deep_equals(val, b_val)) {
            found = TRUE;
            break;
          } else {
            return FALSE;
          }
        }
      }
      if (!found) {
        return FALSE;
      }
    }
      return TRUE;
    }
    default:
      return FALSE;
  }
  return FALSE;
}
static guint G_GNUC_UNUSED flpigeon_deep_hash(FlValue* value) {
  if (value == nullptr) {
    return 0;
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return 0;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(value) ? 1231 : 1237;
    case FL_VALUE_TYPE_INT: {
      int64_t v = fl_value_get_int(value);
      return static_cast<guint>(v ^ (v >> 32));
    }
    case FL_VALUE_TYPE_FLOAT:
      return flpigeon_hash_double(fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_str_hash(fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + data[i];
      }
      return result;
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
      return result;
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i] ^ (data[i] >> 32));
      }
      return result;
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_hash_double(data[i]);
    }
      return result;
    }
    case FL_VALUE_TYPE_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_deep_hash(fl_value_get_list_value(value, i));
    }
      return result;
    }
    case FL_VALUE_TYPE_MAP: {
      guint result = 0;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result += ((flpigeon_deep_hash(fl_value_get_map_key(value, i)) * 31) ^ flpigeon_deep_hash(fl_value_get_map_value(value, i)));
    }
      return result;
    }
    default:
      return static_cast<guint>(fl_value_get_type(value));
  }
  return 0;
}
static gchar* G_GNUC_UNUSED flpigeon_to_string(FlValue* value) {
  if (value == nullptr) {
    return g_strdup("null");
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return g_strdup("null");
    case FL_VALUE_TYPE_BOOL:
      return g_strdup(fl_value_get_bool(value) ? "true" : "false");
    case FL_VALUE_TYPE_INT:
      return g_strdup_printf("%" G_GINT64_FORMAT, fl_value_get_int(value));
    case FL_VALUE_TYPE_FLOAT:
      return g_strdup_printf("%g", fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_strdup_printf("\"%s\"", fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%" G_GINT64_FORMAT, data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%g", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* item_str = flpigeon_to_string(fl_value_get_list_value(value, i));
        g_string_append(str, item_str);
        g_free(item_str);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_MAP: {
      GString* str = g_string_new("{");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* key_str = flpigeon_to_string(fl_value_get_map_key(value, i));
        gchar* val_str = flpigeon_to_string(fl_value_get_map_value(value, i));
        g_string_append_printf(str, "%s: %s", key_str, val_str);
        g_free(key_str);
        g_free(val_str);
      }
      g_string_append(str, "}");
      return g_string_free(str, FALSE);
    }
    default:
      return g_strdup("[custom]");
  }
  return g_strdup("null");
}


struct _ThumbnailRequest {
  GObject parent_instance;

  gchar* video;
  FlValue* headers;
  gchar* thumbnail_path;
  ThumbnailFormat format;
  int64_t max_height;
  int64_t max_width;
  int64_t time_ms;
  int64_t quality;
};

G_DEFINE_TYPE(ThumbnailRequest, thumbnail_request, G_TYPE_OBJECT)

static void thumbnail_request_dispose(GObject* object) {
  ThumbnailRequest* self = THUMBNAIL_REQUEST(object);
  g_clear_pointer(&self->video, g_free);
  g_clear_pointer(&self->headers, fl_value_unref);
  g_clear_pointer(&self->thumbnail_path, g_free);
  G_OBJECT_CLASS(thumbnail_request_parent_class)->dispose(object);
}

static void thumbnail_request_init(ThumbnailRequest* self) {
}

static void thumbnail_request_class_init(ThumbnailRequestClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = thumbnail_request_dispose;
}

ThumbnailRequest* thumbnail_request_new(const gchar* video, FlValue* headers, const gchar* thumbnail_path, ThumbnailFormat format, int64_t max_height, int64_t max_width, int64_t time_ms, int64_t quality) {
  ThumbnailRequest* self = THUMBNAIL_REQUEST(g_object_new(thumbnail_request_get_type(), nullptr));
  self->video = g_strdup(video);
  if (headers != nullptr) {
    self->headers = fl_value_ref(headers);
  }
  else {
    self->headers = nullptr;
  }
  if (thumbnail_path != nullptr) {
    self->thumbnail_path = g_strdup(thumbnail_path);
  }
  else {
    self->thumbnail_path = nullptr;
  }
  self->format = format;
  self->max_height = max_height;
  self->max_width = max_width;
  self->time_ms = time_ms;
  self->quality = quality;
  return self;
}

const gchar* thumbnail_request_get_video(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), nullptr);
  return self->video;
}

FlValue* thumbnail_request_get_headers(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), nullptr);
  return self->headers;
}

const gchar* thumbnail_request_get_thumbnail_path(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), nullptr);
  return self->thumbnail_path;
}

ThumbnailFormat thumbnail_request_get_format(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), static_cast<ThumbnailFormat>(0));
  return self->format;
}

int64_t thumbnail_request_get_max_height(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), 0);
  return self->max_height;
}

int64_t thumbnail_request_get_max_width(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), 0);
  return self->max_width;
}

int64_t thumbnail_request_get_time_ms(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), 0);
  return self->time_ms;
}

int64_t thumbnail_request_get_quality(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), 0);
  return self->quality;
}

static FlValue* thumbnail_request_to_list(ThumbnailRequest* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->video));
  fl_value_append_take(values, self->headers != nullptr ? fl_value_ref(self->headers) : fl_value_new_null());
  fl_value_append_take(values, self->thumbnail_path != nullptr ? fl_value_new_string(self->thumbnail_path) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_custom(thumbnail_format_type_id, fl_value_new_int(self->format), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_int(self->max_height));
  fl_value_append_take(values, fl_value_new_int(self->max_width));
  fl_value_append_take(values, fl_value_new_int(self->time_ms));
  fl_value_append_take(values, fl_value_new_int(self->quality));
  return values;
}

static ThumbnailRequest* thumbnail_request_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* video = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  FlValue* headers = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    headers = value1;
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  const gchar* thumbnail_path = nullptr;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    thumbnail_path = fl_value_get_string(value2);
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  ThumbnailFormat format = static_cast<ThumbnailFormat>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value3)))));
  FlValue* value4 = fl_value_get_list_value(values, 4);
  int64_t max_height = fl_value_get_int(value4);
  FlValue* value5 = fl_value_get_list_value(values, 5);
  int64_t max_width = fl_value_get_int(value5);
  FlValue* value6 = fl_value_get_list_value(values, 6);
  int64_t time_ms = fl_value_get_int(value6);
  FlValue* value7 = fl_value_get_list_value(values, 7);
  int64_t quality = fl_value_get_int(value7);
  return thumbnail_request_new(video, headers, thumbnail_path, format, max_height, max_width, time_ms, quality);
}

gboolean thumbnail_request_equals(ThumbnailRequest* a, ThumbnailRequest* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->video, b->video) != 0) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->headers, b->headers)) {
    return FALSE;
  }
  if (g_strcmp0(a->thumbnail_path, b->thumbnail_path) != 0) {
    return FALSE;
  }
  if (a->format != b->format) {
    return FALSE;
  }
  if (a->max_height != b->max_height) {
    return FALSE;
  }
  if (a->max_width != b->max_width) {
    return FALSE;
  }
  if (a->time_ms != b->time_ms) {
    return FALSE;
  }
  if (a->quality != b->quality) {
    return FALSE;
  }
  return TRUE;
}

guint thumbnail_request_hash(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), 0);
  guint result = 0;
  result = result * 31 + (self->video != nullptr ? g_str_hash(self->video) : 0);
  result = result * 31 + flpigeon_deep_hash(self->headers);
  result = result * 31 + (self->thumbnail_path != nullptr ? g_str_hash(self->thumbnail_path) : 0);
  result = result * 31 + static_cast<guint>(self->format);
  result = result * 31 + static_cast<guint>(self->max_height);
  result = result * 31 + static_cast<guint>(self->max_width);
  result = result * 31 + static_cast<guint>(self->time_ms);
  result = result * 31 + static_cast<guint>(self->quality);
  return result;
}

gchar* thumbnail_request_to_string(ThumbnailRequest* self) {
  g_return_val_if_fail(_IS_THUMBNAIL_REQUEST(self), NULL);
  GString* str = g_string_new("ThumbnailRequest(");
  g_string_append(str, "video: ");
  if (self->video != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->video);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", headers: ");
  if (self->headers != nullptr) {
    gchar* val_str = flpigeon_to_string(self->headers);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", thumbnail_path: ");
  if (self->thumbnail_path != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->thumbnail_path);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", format: ");
  g_string_append_printf(str, "%d", static_cast<int>(self->format));
  g_string_append(str, ", max_height: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->max_height);
  g_string_append(str, ", max_width: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->max_width);
  g_string_append(str, ", time_ms: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->time_ms);
  g_string_append(str, ", quality: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->quality);
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _MessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(MessageCodec, message_codec, fl_standard_message_codec_get_type())

const int thumbnail_format_type_id = 129;
const int thumbnail_request_type_id = 130;

static gboolean message_codec_write_thumbnail_format(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = thumbnail_format_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean message_codec_write_thumbnail_request(FlStandardMessageCodec* codec, GByteArray* buffer, ThumbnailRequest* value, GError** error) {
  uint8_t type = thumbnail_request_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = thumbnail_request_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case thumbnail_format_type_id:
        return message_codec_write_thumbnail_format(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case thumbnail_request_type_id:
        return message_codec_write_thumbnail_request(codec, buffer, THUMBNAIL_REQUEST(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* message_codec_read_thumbnail_format(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(thumbnail_format_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* message_codec_read_thumbnail_request(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(ThumbnailRequest) value = thumbnail_request_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(thumbnail_request_type_id, G_OBJECT(value));
}

static FlValue* message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case thumbnail_format_type_id:
      return message_codec_read_thumbnail_format(codec, buffer, offset, error);
    case thumbnail_request_type_id:
      return message_codec_read_thumbnail_request(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void message_codec_init(MessageCodec* self) {
}

static void message_codec_class_init(MessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = message_codec_read_value_of_type;
}

static MessageCodec* message_codec_new() {
  MessageCodec* self = MESSAGE_CODEC(g_object_new(message_codec_get_type(), nullptr));
  return self;
}

struct _StreamThumbnailHostApiResponseHandle {
  GObject parent_instance;

  FlBasicMessageChannel* channel;
  FlBasicMessageChannelResponseHandle* response_handle;
};

G_DEFINE_TYPE(StreamThumbnailHostApiResponseHandle, stream_thumbnail_host_api_response_handle, G_TYPE_OBJECT)

static void stream_thumbnail_host_api_response_handle_dispose(GObject* object) {
  StreamThumbnailHostApiResponseHandle* self = STREAM_THUMBNAIL_HOST_API_RESPONSE_HANDLE(object);
  g_clear_object(&self->channel);
  g_clear_object(&self->response_handle);
  G_OBJECT_CLASS(stream_thumbnail_host_api_response_handle_parent_class)->dispose(object);
}

static void stream_thumbnail_host_api_response_handle_init(StreamThumbnailHostApiResponseHandle* self) {
}

static void stream_thumbnail_host_api_response_handle_class_init(StreamThumbnailHostApiResponseHandleClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = stream_thumbnail_host_api_response_handle_dispose;
}

static StreamThumbnailHostApiResponseHandle* stream_thumbnail_host_api_response_handle_new(FlBasicMessageChannel* channel, FlBasicMessageChannelResponseHandle* response_handle) {
  StreamThumbnailHostApiResponseHandle* self = STREAM_THUMBNAIL_HOST_API_RESPONSE_HANDLE(g_object_new(stream_thumbnail_host_api_response_handle_get_type(), nullptr));
  self->channel = FL_BASIC_MESSAGE_CHANNEL(g_object_ref(channel));
  self->response_handle = FL_BASIC_MESSAGE_CHANNEL_RESPONSE_HANDLE(g_object_ref(response_handle));
  return self;
}

G_DECLARE_FINAL_TYPE(StreamThumbnailHostApiThumbnailDataResponse, stream_thumbnail_host_api_thumbnail_data_response, , STREAM_THUMBNAIL_HOST_API_THUMBNAIL_DATA_RESPONSE, GObject)

struct _StreamThumbnailHostApiThumbnailDataResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(StreamThumbnailHostApiThumbnailDataResponse, stream_thumbnail_host_api_thumbnail_data_response, G_TYPE_OBJECT)

static void stream_thumbnail_host_api_thumbnail_data_response_dispose(GObject* object) {
  StreamThumbnailHostApiThumbnailDataResponse* self = STREAM_THUMBNAIL_HOST_API_THUMBNAIL_DATA_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(stream_thumbnail_host_api_thumbnail_data_response_parent_class)->dispose(object);
}

static void stream_thumbnail_host_api_thumbnail_data_response_init(StreamThumbnailHostApiThumbnailDataResponse* self) {
}

static void stream_thumbnail_host_api_thumbnail_data_response_class_init(StreamThumbnailHostApiThumbnailDataResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = stream_thumbnail_host_api_thumbnail_data_response_dispose;
}

static StreamThumbnailHostApiThumbnailDataResponse* stream_thumbnail_host_api_thumbnail_data_response_new(const uint8_t* return_value, size_t return_value_length) {
  StreamThumbnailHostApiThumbnailDataResponse* self = STREAM_THUMBNAIL_HOST_API_THUMBNAIL_DATA_RESPONSE(g_object_new(stream_thumbnail_host_api_thumbnail_data_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_uint8_list(return_value, return_value_length));
  return self;
}

static StreamThumbnailHostApiThumbnailDataResponse* stream_thumbnail_host_api_thumbnail_data_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  StreamThumbnailHostApiThumbnailDataResponse* self = STREAM_THUMBNAIL_HOST_API_THUMBNAIL_DATA_RESPONSE(g_object_new(stream_thumbnail_host_api_thumbnail_data_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(StreamThumbnailHostApiThumbnailFileResponse, stream_thumbnail_host_api_thumbnail_file_response, , STREAM_THUMBNAIL_HOST_API_THUMBNAIL_FILE_RESPONSE, GObject)

struct _StreamThumbnailHostApiThumbnailFileResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(StreamThumbnailHostApiThumbnailFileResponse, stream_thumbnail_host_api_thumbnail_file_response, G_TYPE_OBJECT)

static void stream_thumbnail_host_api_thumbnail_file_response_dispose(GObject* object) {
  StreamThumbnailHostApiThumbnailFileResponse* self = STREAM_THUMBNAIL_HOST_API_THUMBNAIL_FILE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(stream_thumbnail_host_api_thumbnail_file_response_parent_class)->dispose(object);
}

static void stream_thumbnail_host_api_thumbnail_file_response_init(StreamThumbnailHostApiThumbnailFileResponse* self) {
}

static void stream_thumbnail_host_api_thumbnail_file_response_class_init(StreamThumbnailHostApiThumbnailFileResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = stream_thumbnail_host_api_thumbnail_file_response_dispose;
}

static StreamThumbnailHostApiThumbnailFileResponse* stream_thumbnail_host_api_thumbnail_file_response_new(const gchar* return_value) {
  StreamThumbnailHostApiThumbnailFileResponse* self = STREAM_THUMBNAIL_HOST_API_THUMBNAIL_FILE_RESPONSE(g_object_new(stream_thumbnail_host_api_thumbnail_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

static StreamThumbnailHostApiThumbnailFileResponse* stream_thumbnail_host_api_thumbnail_file_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  StreamThumbnailHostApiThumbnailFileResponse* self = STREAM_THUMBNAIL_HOST_API_THUMBNAIL_FILE_RESPONSE(g_object_new(stream_thumbnail_host_api_thumbnail_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _StreamThumbnailHostApi {
  GObject parent_instance;

  const StreamThumbnailHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(StreamThumbnailHostApi, stream_thumbnail_host_api, G_TYPE_OBJECT)

static void stream_thumbnail_host_api_dispose(GObject* object) {
  StreamThumbnailHostApi* self = STREAM_THUMBNAIL_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(stream_thumbnail_host_api_parent_class)->dispose(object);
}

static void stream_thumbnail_host_api_init(StreamThumbnailHostApi* self) {
}

static void stream_thumbnail_host_api_class_init(StreamThumbnailHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = stream_thumbnail_host_api_dispose;
}

static StreamThumbnailHostApi* stream_thumbnail_host_api_new(const StreamThumbnailHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  StreamThumbnailHostApi* self = STREAM_THUMBNAIL_HOST_API(g_object_new(stream_thumbnail_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void stream_thumbnail_host_api_thumbnail_data_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  StreamThumbnailHostApi* self = STREAM_THUMBNAIL_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->thumbnail_data == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  ThumbnailRequest* request = THUMBNAIL_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(StreamThumbnailHostApiResponseHandle) handle = stream_thumbnail_host_api_response_handle_new(channel, response_handle);
  self->vtable->thumbnail_data(request, handle, self->user_data);
}

static void stream_thumbnail_host_api_thumbnail_file_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  StreamThumbnailHostApi* self = STREAM_THUMBNAIL_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->thumbnail_file == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  ThumbnailRequest* request = THUMBNAIL_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(StreamThumbnailHostApiResponseHandle) handle = stream_thumbnail_host_api_response_handle_new(channel, response_handle);
  self->vtable->thumbnail_file(request, handle, self->user_data);
}

void stream_thumbnail_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const StreamThumbnailHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(StreamThumbnailHostApi) api_data = stream_thumbnail_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(MessageCodec) codec = message_codec_new();
  g_autofree gchar* thumbnail_data_channel_name = g_strdup_printf("dev.flutter.pigeon.stream_thumbnail.StreamThumbnailHostApi.thumbnailData%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) thumbnail_data_channel = fl_basic_message_channel_new(messenger, thumbnail_data_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(thumbnail_data_channel, stream_thumbnail_host_api_thumbnail_data_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* thumbnail_file_channel_name = g_strdup_printf("dev.flutter.pigeon.stream_thumbnail.StreamThumbnailHostApi.thumbnailFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) thumbnail_file_channel = fl_basic_message_channel_new(messenger, thumbnail_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(thumbnail_file_channel, stream_thumbnail_host_api_thumbnail_file_cb, g_object_ref(api_data), g_object_unref);
}

void stream_thumbnail_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(MessageCodec) codec = message_codec_new();
  g_autofree gchar* thumbnail_data_channel_name = g_strdup_printf("dev.flutter.pigeon.stream_thumbnail.StreamThumbnailHostApi.thumbnailData%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) thumbnail_data_channel = fl_basic_message_channel_new(messenger, thumbnail_data_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(thumbnail_data_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* thumbnail_file_channel_name = g_strdup_printf("dev.flutter.pigeon.stream_thumbnail.StreamThumbnailHostApi.thumbnailFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) thumbnail_file_channel = fl_basic_message_channel_new(messenger, thumbnail_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(thumbnail_file_channel, nullptr, nullptr, nullptr);
}

void stream_thumbnail_host_api_respond_thumbnail_data(StreamThumbnailHostApiResponseHandle* response_handle, const uint8_t* return_value, size_t return_value_length) {
  g_autoptr(StreamThumbnailHostApiThumbnailDataResponse) response = stream_thumbnail_host_api_thumbnail_data_response_new(return_value, return_value_length);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "StreamThumbnailHostApi", "thumbnailData", error->message);
  }
}

void stream_thumbnail_host_api_respond_error_thumbnail_data(StreamThumbnailHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(StreamThumbnailHostApiThumbnailDataResponse) response = stream_thumbnail_host_api_thumbnail_data_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "StreamThumbnailHostApi", "thumbnailData", error->message);
  }
}

void stream_thumbnail_host_api_respond_thumbnail_file(StreamThumbnailHostApiResponseHandle* response_handle, const gchar* return_value) {
  g_autoptr(StreamThumbnailHostApiThumbnailFileResponse) response = stream_thumbnail_host_api_thumbnail_file_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "StreamThumbnailHostApi", "thumbnailFile", error->message);
  }
}

void stream_thumbnail_host_api_respond_error_thumbnail_file(StreamThumbnailHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(StreamThumbnailHostApiThumbnailFileResponse) response = stream_thumbnail_host_api_thumbnail_file_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "StreamThumbnailHostApi", "thumbnailFile", error->message);
  }
}
