// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * StreamThumbnailThumbnailFormat:
 * STREAM_THUMBNAIL_THUMBNAIL_FORMAT_JPEG:
 * STREAM_THUMBNAIL_THUMBNAIL_FORMAT_PNG:
 * STREAM_THUMBNAIL_THUMBNAIL_FORMAT_WEBP:
 *
 * Wire representation of the image format for a generated thumbnail.
 */
typedef enum {
  STREAM_THUMBNAIL_THUMBNAIL_FORMAT_JPEG = 0,
  STREAM_THUMBNAIL_THUMBNAIL_FORMAT_PNG = 1,
  STREAM_THUMBNAIL_THUMBNAIL_FORMAT_WEBP = 2
} StreamThumbnailThumbnailFormat;

/**
 * StreamThumbnailThumbnailRequest:
 *
 * A single thumbnail generation request sent to the native platform.
 */

G_DECLARE_FINAL_TYPE(StreamThumbnailThumbnailRequest, stream_thumbnail_thumbnail_request, STREAM_THUMBNAIL, THUMBNAIL_REQUEST, GObject)

/**
 * stream_thumbnail_thumbnail_request_new:
 * video: field in this object.
 * headers: field in this object.
 * thumbnail_path: field in this object.
 * format: field in this object.
 * max_height: field in this object.
 * max_width: field in this object.
 * time_ms: field in this object.
 * quality: field in this object.
 *
 * Creates a new #ThumbnailRequest object.
 *
 * Returns: a new #StreamThumbnailThumbnailRequest
 */
StreamThumbnailThumbnailRequest* stream_thumbnail_thumbnail_request_new(const gchar* video, FlValue* headers, const gchar* thumbnail_path, StreamThumbnailThumbnailFormat format, int64_t max_height, int64_t max_width, int64_t time_ms, int64_t quality);

/**
 * stream_thumbnail_thumbnail_request_get_video
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the video field of @object.
 *
 * Returns: the field value.
 */
const gchar* stream_thumbnail_thumbnail_request_get_video(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_headers
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the headers field of @object.
 *
 * Returns: the field value.
 */
FlValue* stream_thumbnail_thumbnail_request_get_headers(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_thumbnail_path
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the thumbnailPath field of @object.
 *
 * Returns: the field value.
 */
const gchar* stream_thumbnail_thumbnail_request_get_thumbnail_path(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_format
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the format field of @object.
 *
 * Returns: the field value.
 */
StreamThumbnailThumbnailFormat stream_thumbnail_thumbnail_request_get_format(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_max_height
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the maxHeight field of @object.
 *
 * Returns: the field value.
 */
int64_t stream_thumbnail_thumbnail_request_get_max_height(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_max_width
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the maxWidth field of @object.
 *
 * Returns: the field value.
 */
int64_t stream_thumbnail_thumbnail_request_get_max_width(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_time_ms
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the timeMs field of @object.
 *
 * Returns: the field value.
 */
int64_t stream_thumbnail_thumbnail_request_get_time_ms(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_get_quality
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Gets the value of the quality field of @object.
 *
 * Returns: the field value.
 */
int64_t stream_thumbnail_thumbnail_request_get_quality(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_equals:
 * @a: a #StreamThumbnailThumbnailRequest.
 * @b: another #StreamThumbnailThumbnailRequest.
 *
 * Checks if two #StreamThumbnailThumbnailRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean stream_thumbnail_thumbnail_request_equals(StreamThumbnailThumbnailRequest* a, StreamThumbnailThumbnailRequest* b);

/**
 * stream_thumbnail_thumbnail_request_hash:
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Calculates a hash code for a #StreamThumbnailThumbnailRequest object.
 *
 * Returns: the hash code.
 */
guint stream_thumbnail_thumbnail_request_hash(StreamThumbnailThumbnailRequest* object);

/**
 * stream_thumbnail_thumbnail_request_to_string:
 * @object: a #StreamThumbnailThumbnailRequest.
 *
 * Returns a string representation of a #StreamThumbnailThumbnailRequest object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* stream_thumbnail_thumbnail_request_to_string(StreamThumbnailThumbnailRequest* object);

G_DECLARE_FINAL_TYPE(StreamThumbnailMessageCodec, stream_thumbnail_message_codec, STREAM_THUMBNAIL, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int stream_thumbnail_thumbnail_format_type_id;
extern const int stream_thumbnail_thumbnail_request_type_id;

G_DECLARE_FINAL_TYPE(StreamThumbnailStreamThumbnailHostApi, stream_thumbnail_stream_thumbnail_host_api, STREAM_THUMBNAIL, STREAM_THUMBNAIL_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(StreamThumbnailStreamThumbnailHostApiResponseHandle, stream_thumbnail_stream_thumbnail_host_api_response_handle, STREAM_THUMBNAIL, STREAM_THUMBNAIL_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * StreamThumbnailStreamThumbnailHostApiVTable:
 *
 * Table of functions exposed by StreamThumbnailHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*thumbnail_data)(StreamThumbnailThumbnailRequest* request, StreamThumbnailStreamThumbnailHostApiResponseHandle* response_handle, gpointer user_data);
  void (*thumbnail_file)(StreamThumbnailThumbnailRequest* request, StreamThumbnailStreamThumbnailHostApiResponseHandle* response_handle, gpointer user_data);
} StreamThumbnailStreamThumbnailHostApiVTable;

/**
 * stream_thumbnail_stream_thumbnail_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the StreamThumbnailHostApi API.
 */
void stream_thumbnail_stream_thumbnail_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const StreamThumbnailStreamThumbnailHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * stream_thumbnail_stream_thumbnail_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the StreamThumbnailHostApi API.
 */
void stream_thumbnail_stream_thumbnail_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * stream_thumbnail_stream_thumbnail_host_api_respond_thumbnail_data:
 * @response_handle: a #StreamThumbnailStreamThumbnailHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 * @return_value_length: (allow-none): location to write length of @return_value or %NULL to ignore.
 *
 * Responds to StreamThumbnailHostApi.thumbnailData. 
 */
void stream_thumbnail_stream_thumbnail_host_api_respond_thumbnail_data(StreamThumbnailStreamThumbnailHostApiResponseHandle* response_handle, const uint8_t* return_value, size_t return_value_length);

/**
 * stream_thumbnail_stream_thumbnail_host_api_respond_error_thumbnail_data:
 * @response_handle: a #StreamThumbnailStreamThumbnailHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to StreamThumbnailHostApi.thumbnailData. 
 */
void stream_thumbnail_stream_thumbnail_host_api_respond_error_thumbnail_data(StreamThumbnailStreamThumbnailHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * stream_thumbnail_stream_thumbnail_host_api_respond_thumbnail_file:
 * @response_handle: a #StreamThumbnailStreamThumbnailHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to StreamThumbnailHostApi.thumbnailFile. 
 */
void stream_thumbnail_stream_thumbnail_host_api_respond_thumbnail_file(StreamThumbnailStreamThumbnailHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * stream_thumbnail_stream_thumbnail_host_api_respond_error_thumbnail_file:
 * @response_handle: a #StreamThumbnailStreamThumbnailHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to StreamThumbnailHostApi.thumbnailFile. 
 */
void stream_thumbnail_stream_thumbnail_host_api_respond_error_thumbnail_file(StreamThumbnailStreamThumbnailHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
