// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/generate_icons.dart
//
// To regenerate: melos run generate:icons

import 'package:flutter/widgets.dart';
import 'package:svg_icon_widget/svg_icon_widget.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';
part 'stream_icons.g.theme.dart';
part 'stream_icons.g.dart';

/// Provides customizable icons for the Stream design system.
///
/// [StreamIcons] allows customization of icons used throughout Stream widgets.
/// Each icon is exposed as a field that defaults to the corresponding
/// [StreamIconData] constant.
///
/// {@tool snippet}
///
/// Access icons via context:
///
/// ```dart
/// final icon = context.streamIcons.settingsGear2;
/// ```
/// {@end-tool}
///
/// {@tool snippet}
///
/// Override specific icons in [StreamTheme]:
///
/// ```dart
/// StreamTheme(
///   icons: StreamIcons(
///     settingsGear2: Icons.settings_outlined,
///     lock: Icons.lock_outline,
///   ),
/// )
/// ```
/// {@end-tool}
///
/// {@tool snippet}
///
/// Use copyWith for partial overrides:
///
/// ```dart
/// final customIcons = const StreamIcons().copyWith(
///   settingsGear2: Icons.settings_outlined,
/// );
/// ```
/// {@end-tool}
///
/// See also:
///
///  * [StreamIconData], which contains the raw icon data constants.
///  * [StreamTheme], which accepts custom icons via the [icons] parameter.
@themeGen
@immutable
class StreamIcons with _$StreamIcons {
  /// Creates an icon set with optional overrides.
  const StreamIcons({
    this.account = StreamIconData.account,
    this.archive = StreamIconData.archive,
    this.arrowDown = StreamIconData.arrowDown,
    this.arrowDownCircle = StreamIconData.arrowDownCircle,
    this.arrowLeft = StreamIconData.arrowLeft,
    this.arrowRight = StreamIconData.arrowRight,
    this.arrowUp = StreamIconData.arrowUp,
    this.arrowUpRight = StreamIconData.arrowUpRight,
    this.attachment = StreamIconData.attachment,
    this.audio = StreamIconData.audio,
    this.bell = StreamIconData.bell,
    this.bellOff = StreamIconData.bellOff,
    this.blurFill = StreamIconData.blurFill,
    this.bolt = StreamIconData.bolt,
    this.boltFill = StreamIconData.boltFill,
    this.camera = StreamIconData.camera,
    this.cameraFlipFill = StreamIconData.cameraFlipFill,
    this.cameraLarge = StreamIconData.cameraLarge,
    this.captionFill = StreamIconData.captionFill,
    this.caretDown = StreamIconData.caretDown,
    this.caretUp = StreamIconData.caretUp,
    this.checkmark = StreamIconData.checkmark,
    this.checks = StreamIconData.checks,
    this.chevronDown = StreamIconData.chevronDown,
    this.chevronLeft = StreamIconData.chevronLeft,
    this.chevronRight = StreamIconData.chevronRight,
    this.chevronUp = StreamIconData.chevronUp,
    this.clock = StreamIconData.clock,
    this.command = StreamIconData.command,
    this.copy = StreamIconData.copy,
    this.copyFill = StreamIconData.copyFill,
    this.darkMode = StreamIconData.darkMode,
    this.delete = StreamIconData.delete,
    this.download = StreamIconData.download,
    this.edit = StreamIconData.edit,
    this.emoji = StreamIconData.emoji,
    this.emojiAdd = StreamIconData.emojiAdd,
    this.emojiAddFill = StreamIconData.emojiAddFill,
    this.exclamationCircle = StreamIconData.exclamationCircle,
    this.exclamationCircleFill = StreamIconData.exclamationCircleFill,
    this.exclamationMarkFill = StreamIconData.exclamationMarkFill,
    this.exclamationTriangleFill = StreamIconData.exclamationTriangleFill,
    this.export = StreamIconData.export,
    this.eyeFill = StreamIconData.eyeFill,
    this.file = StreamIconData.file,
    this.flag = StreamIconData.flag,
    this.folder = StreamIconData.folder,
    this.folderLarge = StreamIconData.folderLarge,
    this.fullBlurFill = StreamIconData.fullBlurFill,
    this.fullscreenFill = StreamIconData.fullscreenFill,
    this.gallery = StreamIconData.gallery,
    this.gridFill = StreamIconData.gridFill,
    this.gridPixelFill = StreamIconData.gridPixelFill,
    this.image = StreamIconData.image,
    this.imageLarge = StreamIconData.imageLarge,
    this.info = StreamIconData.info,
    this.language = StreamIconData.language,
    this.leave = StreamIconData.leave,
    this.leftToRight = StreamIconData.leftToRight,
    this.lightMode = StreamIconData.lightMode,
    this.link = StreamIconData.link,
    this.location = StreamIconData.location,
    this.lock = StreamIconData.lock,
    this.megaphone = StreamIconData.megaphone,
    this.mention = StreamIconData.mention,
    this.menu = StreamIconData.menu,
    this.messageBubble = StreamIconData.messageBubble,
    this.messageBubbleFill = StreamIconData.messageBubbleFill,
    this.messageBubbleLarge = StreamIconData.messageBubbleLarge,
    this.messageBubbles = StreamIconData.messageBubbles,
    this.messageBubblesFill = StreamIconData.messageBubblesFill,
    this.messageBubblesLarge = StreamIconData.messageBubblesLarge,
    this.minus = StreamIconData.minus,
    this.minusCircle = StreamIconData.minusCircle,
    this.more = StreamIconData.more,
    this.moreHorizontal = StreamIconData.moreHorizontal,
    this.moreVerticalFill = StreamIconData.moreVerticalFill,
    this.mute = StreamIconData.mute,
    this.noSign = StreamIconData.noSign,
    this.noSignFill = StreamIconData.noSignFill,
    this.notification = StreamIconData.notification,
    this.pauseFill = StreamIconData.pauseFill,
    this.phoneDownFill = StreamIconData.phoneDownFill,
    this.pin = StreamIconData.pin,
    this.pinFill = StreamIconData.pinFill,
    this.pinLarge = StreamIconData.pinLarge,
    this.pipFill = StreamIconData.pipFill,
    this.playFill = StreamIconData.playFill,
    this.plus = StreamIconData.plus,
    this.poll = StreamIconData.poll,
    this.pollLarge = StreamIconData.pollLarge,
    this.presentDesktopFill = StreamIconData.presentDesktopFill,
    this.presentMobileFill = StreamIconData.presentMobileFill,
    this.questionCircleFill = StreamIconData.questionCircleFill,
    this.quote = StreamIconData.quote,
    this.raiseHandFill = StreamIconData.raiseHandFill,
    this.recordLibraryFill = StreamIconData.recordLibraryFill,
    this.recordingFill = StreamIconData.recordingFill,
    this.recordingStopFill = StreamIconData.recordingStopFill,
    this.refresh = StreamIconData.refresh,
    this.reorder = StreamIconData.reorder,
    this.reply = StreamIconData.reply,
    this.retry = StreamIconData.retry,
    this.save = StreamIconData.save,
    this.search = StreamIconData.search,
    this.send = StreamIconData.send,
    this.settings = StreamIconData.settings,
    this.settingsFill = StreamIconData.settingsFill,
    this.share = StreamIconData.share,
    this.shield = StreamIconData.shield,
    this.sidebar = StreamIconData.sidebar,
    this.slidersFill = StreamIconData.slidersFill,
    this.starFill = StreamIconData.starFill,
    this.statsFill = StreamIconData.statsFill,
    this.stopFill = StreamIconData.stopFill,
    this.thread = StreamIconData.thread,
    this.threadFill = StreamIconData.threadFill,
    this.translate = StreamIconData.translate,
    this.trophy = StreamIconData.trophy,
    this.unlock = StreamIconData.unlock,
    this.unpin = StreamIconData.unpin,
    this.unpinFill = StreamIconData.unpinFill,
    this.unsave = StreamIconData.unsave,
    this.unsupportedAttachment = StreamIconData.unsupportedAttachment,
    this.upload = StreamIconData.upload,
    this.user = StreamIconData.user,
    this.userAdd = StreamIconData.userAdd,
    this.userAddFill = StreamIconData.userAddFill,
    this.userCheck = StreamIconData.userCheck,
    this.userRemove = StreamIconData.userRemove,
    this.userRemoveFill = StreamIconData.userRemoveFill,
    this.users = StreamIconData.users,
    this.usersFill = StreamIconData.usersFill,
    this.verifiedFill = StreamIconData.verifiedFill,
    this.video = StreamIconData.video,
    this.videoFill = StreamIconData.videoFill,
    this.videoOffFill = StreamIconData.videoOffFill,
    this.voice = StreamIconData.voice,
    this.voiceFill = StreamIconData.voiceFill,
    this.voiceOffFill = StreamIconData.voiceOffFill,
    this.xCircle = StreamIconData.xCircle,
    this.xmark = StreamIconData.xmark,
    this.xmarkSmall = StreamIconData.xmarkSmall,
    this.giphy = StreamSvgIconData.giphy,
    this.imgur = StreamSvgIconData.imgur,
  });

  /// The account icon.
  final IconData account;

  /// The archive icon.
  final IconData archive;

  /// The arrow down icon.
  final IconData arrowDown;

  /// The arrow down circle icon.
  final IconData arrowDownCircle;

  /// The arrow left icon.
  final IconData arrowLeft;

  /// The arrow right icon.
  final IconData arrowRight;

  /// The arrow up icon.
  final IconData arrowUp;

  /// The arrow up right icon.
  final IconData arrowUpRight;

  /// The attachment icon.
  final IconData attachment;

  /// The audio icon.
  final IconData audio;

  /// The bell icon.
  final IconData bell;

  /// The bell off icon.
  final IconData bellOff;

  /// The blur fill icon.
  final IconData blurFill;

  /// The bolt icon.
  final IconData bolt;

  /// The bolt fill icon.
  final IconData boltFill;

  /// The camera icon.
  final IconData camera;

  /// The camera flip fill icon.
  final IconData cameraFlipFill;

  /// The camera large icon.
  final IconData cameraLarge;

  /// The caption fill icon.
  final IconData captionFill;

  /// The caret down icon.
  final IconData caretDown;

  /// The caret up icon.
  final IconData caretUp;

  /// The checkmark icon.
  final IconData checkmark;

  /// The checks icon.
  final IconData checks;

  /// The chevron down icon.
  final IconData chevronDown;

  /// The chevron left icon.
  final IconData chevronLeft;

  /// The chevron right icon.
  final IconData chevronRight;

  /// The chevron up icon.
  final IconData chevronUp;

  /// The clock icon.
  final IconData clock;

  /// The command icon.
  final IconData command;

  /// The copy icon.
  final IconData copy;

  /// The copy fill icon.
  final IconData copyFill;

  /// The dark mode icon.
  final IconData darkMode;

  /// The delete icon.
  final IconData delete;

  /// The download icon.
  final IconData download;

  /// The edit icon.
  final IconData edit;

  /// The emoji icon.
  final IconData emoji;

  /// The emoji add icon.
  final IconData emojiAdd;

  /// The emoji add fill icon.
  final IconData emojiAddFill;

  /// The exclamation circle icon.
  final IconData exclamationCircle;

  /// The exclamation circle fill icon.
  final IconData exclamationCircleFill;

  /// The exclamation mark fill icon.
  final IconData exclamationMarkFill;

  /// The exclamation triangle fill icon.
  final IconData exclamationTriangleFill;

  /// The export icon.
  final IconData export;

  /// The eye fill icon.
  final IconData eyeFill;

  /// The file icon.
  final IconData file;

  /// The flag icon.
  final IconData flag;

  /// The folder icon.
  final IconData folder;

  /// The folder large icon.
  final IconData folderLarge;

  /// The full blur fill icon.
  final IconData fullBlurFill;

  /// The fullscreen fill icon.
  final IconData fullscreenFill;

  /// The gallery icon.
  final IconData gallery;

  /// The grid fill icon.
  final IconData gridFill;

  /// The grid pixel fill icon.
  final IconData gridPixelFill;

  /// The image icon.
  final IconData image;

  /// The image large icon.
  final IconData imageLarge;

  /// The info icon.
  final IconData info;

  /// The language icon.
  final IconData language;

  /// The leave icon.
  final IconData leave;

  /// The left to right icon.
  final IconData leftToRight;

  /// The light mode icon.
  final IconData lightMode;

  /// The link icon.
  final IconData link;

  /// The location icon.
  final IconData location;

  /// The lock icon.
  final IconData lock;

  /// The megaphone icon.
  final IconData megaphone;

  /// The mention icon.
  final IconData mention;

  /// The menu icon.
  final IconData menu;

  /// The message bubble icon.
  final IconData messageBubble;

  /// The message bubble fill icon.
  final IconData messageBubbleFill;

  /// The message bubble large icon.
  final IconData messageBubbleLarge;

  /// The message bubbles icon.
  final IconData messageBubbles;

  /// The message bubbles fill icon.
  final IconData messageBubblesFill;

  /// The message bubbles large icon.
  final IconData messageBubblesLarge;

  /// The minus icon.
  final IconData minus;

  /// The minus circle icon.
  final IconData minusCircle;

  /// The more icon.
  final IconData more;

  /// The more horizontal icon.
  final IconData moreHorizontal;

  /// The more vertical fill icon.
  final IconData moreVerticalFill;

  /// The mute icon.
  final IconData mute;

  /// The no sign icon.
  final IconData noSign;

  /// The no sign fill icon.
  final IconData noSignFill;

  /// The notification icon.
  final IconData notification;

  /// The pause fill icon.
  final IconData pauseFill;

  /// The phone down fill icon.
  final IconData phoneDownFill;

  /// The pin icon.
  final IconData pin;

  /// The pin fill icon.
  final IconData pinFill;

  /// The pin large icon.
  final IconData pinLarge;

  /// The pip fill icon.
  final IconData pipFill;

  /// The play fill icon.
  final IconData playFill;

  /// The plus icon.
  final IconData plus;

  /// The poll icon.
  final IconData poll;

  /// The poll large icon.
  final IconData pollLarge;

  /// The present desktop fill icon.
  final IconData presentDesktopFill;

  /// The present mobile fill icon.
  final IconData presentMobileFill;

  /// The question circle fill icon.
  final IconData questionCircleFill;

  /// The quote icon.
  final IconData quote;

  /// The raise hand fill icon.
  final IconData raiseHandFill;

  /// The record library fill icon.
  final IconData recordLibraryFill;

  /// The recording fill icon.
  final IconData recordingFill;

  /// The recording stop fill icon.
  final IconData recordingStopFill;

  /// The refresh icon.
  final IconData refresh;

  /// The reorder icon.
  final IconData reorder;

  /// The reply icon.
  final IconData reply;

  /// The retry icon.
  final IconData retry;

  /// The save icon.
  final IconData save;

  /// The search icon.
  final IconData search;

  /// The send icon.
  final IconData send;

  /// The settings icon.
  final IconData settings;

  /// The settings fill icon.
  final IconData settingsFill;

  /// The share icon.
  final IconData share;

  /// The shield icon.
  final IconData shield;

  /// The sidebar icon.
  final IconData sidebar;

  /// The sliders fill icon.
  final IconData slidersFill;

  /// The star fill icon.
  final IconData starFill;

  /// The stats fill icon.
  final IconData statsFill;

  /// The stop fill icon.
  final IconData stopFill;

  /// The thread icon.
  final IconData thread;

  /// The thread fill icon.
  final IconData threadFill;

  /// The translate icon.
  final IconData translate;

  /// The trophy icon.
  final IconData trophy;

  /// The unlock icon.
  final IconData unlock;

  /// The unpin icon.
  final IconData unpin;

  /// The unpin fill icon.
  final IconData unpinFill;

  /// The unsave icon.
  final IconData unsave;

  /// The unsupported attachment icon.
  final IconData unsupportedAttachment;

  /// The upload icon.
  final IconData upload;

  /// The user icon.
  final IconData user;

  /// The user add icon.
  final IconData userAdd;

  /// The user add fill icon.
  final IconData userAddFill;

  /// The user check icon.
  final IconData userCheck;

  /// The user remove icon.
  final IconData userRemove;

  /// The user remove fill icon.
  final IconData userRemoveFill;

  /// The users icon.
  final IconData users;

  /// The users fill icon.
  final IconData usersFill;

  /// The verified fill icon.
  final IconData verifiedFill;

  /// The video icon.
  final IconData video;

  /// The video fill icon.
  final IconData videoFill;

  /// The video off fill icon.
  final IconData videoOffFill;

  /// The voice icon.
  final IconData voice;

  /// The voice fill icon.
  final IconData voiceFill;

  /// The voice off fill icon.
  final IconData voiceOffFill;

  /// The x circle icon.
  final IconData xCircle;

  /// The xmark icon.
  final IconData xmark;

  /// The xmark small icon.
  final IconData xmarkSmall;

  /// The giphy colored SVG icon.
  ///
  /// This is an [SvgIconData] — use with [SvgIcon], not [Icon].
  final SvgIconData giphy;

  /// The imgur colored SVG icon.
  ///
  /// This is an [SvgIconData] — use with [SvgIcon], not [Icon].
  final SvgIconData imgur;

  /// A map of all available icons keyed by their field name.
  ///
  /// Useful for dynamic icon lookup by string name.
  ///
  /// ```dart
  /// final icon = context.streamIcons.allIcons['settingsGear2'];
  /// ```
  Map<String, IconData> get allIcons => {
    'account': account,
    'archive': archive,
    'arrowDown': arrowDown,
    'arrowDownCircle': arrowDownCircle,
    'arrowLeft': arrowLeft,
    'arrowRight': arrowRight,
    'arrowUp': arrowUp,
    'arrowUpRight': arrowUpRight,
    'attachment': attachment,
    'audio': audio,
    'bell': bell,
    'bellOff': bellOff,
    'blurFill': blurFill,
    'bolt': bolt,
    'boltFill': boltFill,
    'camera': camera,
    'cameraFlipFill': cameraFlipFill,
    'cameraLarge': cameraLarge,
    'captionFill': captionFill,
    'caretDown': caretDown,
    'caretUp': caretUp,
    'checkmark': checkmark,
    'checks': checks,
    'chevronDown': chevronDown,
    'chevronLeft': chevronLeft,
    'chevronRight': chevronRight,
    'chevronUp': chevronUp,
    'clock': clock,
    'command': command,
    'copy': copy,
    'copyFill': copyFill,
    'darkMode': darkMode,
    'delete': delete,
    'download': download,
    'edit': edit,
    'emoji': emoji,
    'emojiAdd': emojiAdd,
    'emojiAddFill': emojiAddFill,
    'exclamationCircle': exclamationCircle,
    'exclamationCircleFill': exclamationCircleFill,
    'exclamationMarkFill': exclamationMarkFill,
    'exclamationTriangleFill': exclamationTriangleFill,
    'export': export,
    'eyeFill': eyeFill,
    'file': file,
    'flag': flag,
    'folder': folder,
    'folderLarge': folderLarge,
    'fullBlurFill': fullBlurFill,
    'fullscreenFill': fullscreenFill,
    'gallery': gallery,
    'gridFill': gridFill,
    'gridPixelFill': gridPixelFill,
    'image': image,
    'imageLarge': imageLarge,
    'info': info,
    'language': language,
    'leave': leave,
    'leftToRight': leftToRight,
    'lightMode': lightMode,
    'link': link,
    'location': location,
    'lock': lock,
    'megaphone': megaphone,
    'mention': mention,
    'menu': menu,
    'messageBubble': messageBubble,
    'messageBubbleFill': messageBubbleFill,
    'messageBubbleLarge': messageBubbleLarge,
    'messageBubbles': messageBubbles,
    'messageBubblesFill': messageBubblesFill,
    'messageBubblesLarge': messageBubblesLarge,
    'minus': minus,
    'minusCircle': minusCircle,
    'more': more,
    'moreHorizontal': moreHorizontal,
    'moreVerticalFill': moreVerticalFill,
    'mute': mute,
    'noSign': noSign,
    'noSignFill': noSignFill,
    'notification': notification,
    'pauseFill': pauseFill,
    'phoneDownFill': phoneDownFill,
    'pin': pin,
    'pinFill': pinFill,
    'pinLarge': pinLarge,
    'pipFill': pipFill,
    'playFill': playFill,
    'plus': plus,
    'poll': poll,
    'pollLarge': pollLarge,
    'presentDesktopFill': presentDesktopFill,
    'presentMobileFill': presentMobileFill,
    'questionCircleFill': questionCircleFill,
    'quote': quote,
    'raiseHandFill': raiseHandFill,
    'recordLibraryFill': recordLibraryFill,
    'recordingFill': recordingFill,
    'recordingStopFill': recordingStopFill,
    'refresh': refresh,
    'reorder': reorder,
    'reply': reply,
    'retry': retry,
    'save': save,
    'search': search,
    'send': send,
    'settings': settings,
    'settingsFill': settingsFill,
    'share': share,
    'shield': shield,
    'sidebar': sidebar,
    'slidersFill': slidersFill,
    'starFill': starFill,
    'statsFill': statsFill,
    'stopFill': stopFill,
    'thread': thread,
    'threadFill': threadFill,
    'translate': translate,
    'trophy': trophy,
    'unlock': unlock,
    'unpin': unpin,
    'unpinFill': unpinFill,
    'unsave': unsave,
    'unsupportedAttachment': unsupportedAttachment,
    'upload': upload,
    'user': user,
    'userAdd': userAdd,
    'userAddFill': userAddFill,
    'userCheck': userCheck,
    'userRemove': userRemove,
    'userRemoveFill': userRemoveFill,
    'users': users,
    'usersFill': usersFill,
    'verifiedFill': verifiedFill,
    'video': video,
    'videoFill': videoFill,
    'videoOffFill': videoOffFill,
    'voice': voice,
    'voiceFill': voiceFill,
    'voiceOffFill': voiceOffFill,
    'xCircle': xCircle,
    'xmark': xmark,
    'xmarkSmall': xmarkSmall,
  };

  /// A map of all colored SVG icons keyed by their field name.
  ///
  /// These icons preserve their original colors and should be used with
  /// [SvgIcon] widget, not the standard [Icon] widget.
  ///
  /// ```dart
  /// final icon = context.streamIcons.allSvgIcons['giphy'];
  /// ```
  Map<String, SvgIconData> get allSvgIcons => {'giphy': giphy, 'imgur': imgur};

  /// Linearly interpolate between two [StreamIcons] objects.
  static StreamIcons? lerp(
    StreamIcons? a,
    StreamIcons? b,
    double t,
  ) => _$StreamIcons.lerp(a, b, t);
}
