// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/generate_icons.dart
//
// To regenerate: melos run generate:icons

import 'package:flutter/widgets.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';
import 'stream_icons.g.dart';
part 'stream_icons.g.theme.dart';

/// Provides customizable icons for the Stream design system.
///
/// [StreamIcons] allows customization of icons used throughout Stream widgets.
/// Each icon is exposed as a field that defaults to the corresponding
/// [StreamIconData] constant.
///
/// {@tool snippet}
///
/// Access icons via context:
///
/// ```dart
/// final icon = context.streamIcons.settingsGear2;
/// ```
/// {@end-tool}
///
/// {@tool snippet}
///
/// Override specific icons in [StreamTheme]:
///
/// ```dart
/// StreamTheme(
///   icons: StreamIcons(
///     settingsGear2: Icons.settings_outlined,
///     lock: Icons.lock_outline,
///   ),
/// )
/// ```
/// {@end-tool}
///
/// {@tool snippet}
///
/// Use copyWith for partial overrides:
///
/// ```dart
/// final customIcons = const StreamIcons().copyWith(
///   settingsGear2: Icons.settings_outlined,
/// );
/// ```
/// {@end-tool}
///
/// See also:
///
///  * [StreamIconData], which contains the raw icon data constants.
///  * [StreamTheme], which accepts custom icons via the [icons] parameter.
@themeGen
@immutable
class StreamIcons with _$StreamIcons {
  /// Creates an icon set with optional overrides.
  const StreamIcons({
    this.apiAggregate = StreamIconData.iconApiAggregate,
    this.apples = StreamIconData.iconApples,
    this.arrowBoxLeft = StreamIconData.iconArrowBoxLeft,
    this.arrowDown = StreamIconData.iconArrowDown,
    this.arrowLeft = StreamIconData.iconArrowLeft,
    this.arrowRight = StreamIconData.iconArrowRight,
    this.arrowRotateClockwise = StreamIconData.iconArrowRotateClockwise,
    this.arrowRotateRightLeftRepeatRefresh = StreamIconData.iconArrowRotateRightLeftRepeatRefresh,
    this.arrowShareLeft = StreamIconData.iconArrowShareLeft,
    this.arrowUp = StreamIconData.iconArrowUp,
    this.arrowsRepeatLeftRight = StreamIconData.iconArrowsRepeatLeftRight,
    this.at = StreamIconData.iconAt,
    this.atSolid = StreamIconData.iconAtSolid,
    this.bellNotification = StreamIconData.iconBellNotification,
    this.browserAISparkle = StreamIconData.iconBrowserAISparkle,
    this.bubble3ChatMessage = StreamIconData.iconBubble3ChatMessage,
    this.bubble3Solid = StreamIconData.iconBubble3Solid,
    this.bubbleAnnotation2ChatMessage = StreamIconData.iconBubbleAnnotation2ChatMessage,
    this.bubbleText6ChatMessage = StreamIconData.iconBubbleText6ChatMessage,
    this.bubbleText6Solid = StreamIconData.iconBubbleText6Solid,
    this.bubbleWideNotificationChatMessage = StreamIconData.iconBubbleWideNotificationChatMessage,
    this.bubbleWideSparkleChatMessage = StreamIconData.iconBubbleWideSparkleChatMessage,
    this.calendar1 = StreamIconData.iconCalendar1,
    this.callCancel = StreamIconData.iconCallCancel,
    this.camera1 = StreamIconData.iconCamera1,
    this.car1 = StreamIconData.iconCar1,
    this.cat = StreamIconData.iconCat,
    this.chainLink3 = StreamIconData.iconChainLink3,
    this.chart5 = StreamIconData.iconChart5,
    this.checkmark1Small = StreamIconData.iconCheckmark1Small,
    this.checkmark2 = StreamIconData.iconCheckmark2,
    this.checkmark2Small = StreamIconData.iconCheckmark2Small,
    this.chevronDown = StreamIconData.iconChevronDown,
    this.chevronGrabberVerticalSelector = StreamIconData.iconChevronGrabberVerticalSelector,
    this.chevronLeft = StreamIconData.iconChevronLeft,
    this.chevronRight = StreamIconData.iconChevronRight,
    this.chevronTop = StreamIconData.iconChevronTop,
    this.circleBanSign = StreamIconData.iconCircleBanSign,
    this.circleCheck = StreamIconData.iconCircleCheck,
    this.circleInfoTooltip = StreamIconData.iconCircleInfoTooltip,
    this.circleMinus = StreamIconData.iconCircleMinus,
    this.circleQuestionmark = StreamIconData.iconCircleQuestionmark,
    this.circleQuestionmarkFilled = StreamIconData.iconCircleQuestionmarkFilled,
    this.circleX = StreamIconData.iconCircleX,
    this.clock = StreamIconData.iconClock,
    this.clockSolid = StreamIconData.iconClockSolid,
    this.code = StreamIconData.iconCode,
    this.codeBrackets = StreamIconData.iconCodeBrackets,
    this.codeEditorInsert = StreamIconData.iconCodeEditorInsert,
    this.compass = StreamIconData.iconCompass,
    this.creditCard2Billing = StreamIconData.iconCreditCard2Billing,
    this.crossMedium = StreamIconData.iconCrossMedium,
    this.crossSmall = StreamIconData.iconCrossSmall,
    this.dotGrid2x3 = StreamIconData.iconDotGrid2x3,
    this.dotsGrid1x3Vertical = StreamIconData.iconDotsGrid1x3Vertical,
    this.doupleCheckmark1Small = StreamIconData.iconDoupleCheckmark1Small,
    this.editBig = StreamIconData.iconEditBig,
    this.editBigSolid = StreamIconData.iconEditBigSolid,
    this.emojiAddReaction = StreamIconData.iconEmojiAddReaction,
    this.emojiSmile = StreamIconData.iconEmojiSmile,
    this.exclamationCircle = StreamIconData.iconExclamationCircle,
    this.exclamationCircle1 = StreamIconData.iconExclamationCircle1,
    this.exclamationTriangle = StreamIconData.iconExclamationTriangle,
    this.exclamationTriangle1 = StreamIconData.iconExclamationTriangle1,
    this.eyeOpen = StreamIconData.iconEyeOpen,
    this.fileBend = StreamIconData.iconFileBend,
    this.filledCircleInfoTooltip = StreamIconData.iconFilledCircleInfoTooltip,
    this.filter1 = StreamIconData.iconFilter1,
    this.flag2 = StreamIconData.iconFlag2,
    this.gauge = StreamIconData.iconGauge,
    this.google = StreamIconData.iconGoogle,
    this.hashtagChannel = StreamIconData.iconHashtagChannel,
    this.heart2 = StreamIconData.iconHeart2,
    this.history = StreamIconData.iconHistory,
    this.images1Alt = StreamIconData.iconImages1Alt,
    this.invite = StreamIconData.iconInvite,
    this.layersBehind = StreamIconData.iconLayersBehind,
    this.layoutGrid1 = StreamIconData.iconLayoutGrid1,
    this.lightBulbSimple = StreamIconData.iconLightBulbSimple,
    this.limits = StreamIconData.iconLimits,
    this.lineChart3 = StreamIconData.iconLineChart3,
    this.lock = StreamIconData.iconLock,
    this.magnifyingGlassSearch = StreamIconData.iconMagnifyingGlassSearch,
    this.mapPin = StreamIconData.iconMapPin,
    this.microphone = StreamIconData.iconMicrophone,
    this.microphoneSolid = StreamIconData.iconMicrophoneSolid,
    this.minusLarge = StreamIconData.iconMinusLarge,
    this.minusSmall = StreamIconData.iconMinusSmall,
    this.mute = StreamIconData.iconMute,
    this.newspaper2 = StreamIconData.iconNewspaper2,
    this.organization = StreamIconData.iconOrganization,
    this.paperPlane = StreamIconData.iconPaperPlane,
    this.paperPlaneTopRight = StreamIconData.iconPaperPlaneTopRight,
    this.paperclip1 = StreamIconData.iconPaperclip1,
    this.paragraphsText = StreamIconData.iconParagraphsText,
    this.pause = StreamIconData.iconPause,
    this.pencil = StreamIconData.iconPencil,
    this.people = StreamIconData.iconPeople,
    this.people2 = StreamIconData.iconPeople2,
    this.peopleAdd = StreamIconData.iconPeopleAdd,
    this.peopleAdded = StreamIconData.iconPeopleAdded,
    this.peopleCircle = StreamIconData.iconPeopleCircle,
    this.peopleCopy = StreamIconData.iconPeopleCopy,
    this.peopleEditUserRights = StreamIconData.iconPeopleEditUserRights,
    this.peopleRemove = StreamIconData.iconPeopleRemove,
    this.persona = StreamIconData.iconPersona,
    this.pin = StreamIconData.iconPin,
    this.playSolid = StreamIconData.iconPlaySolid,
    this.plusLarge = StreamIconData.iconPlusLarge,
    this.plusSmall = StreamIconData.iconPlusSmall,
    this.runShortcut = StreamIconData.iconRunShortcut,
    this.searchText = StreamIconData.iconSearchText,
    this.settingsGear2 = StreamIconData.iconSettingsGear2,
    this.settingsSliderVer = StreamIconData.iconSettingsSliderVer,
    this.shapesPlusCloseSquareCircle = StreamIconData.iconShapesPlusCloseSquareCircle,
    this.shapesTriangleSquareCircle = StreamIconData.iconShapesTriangleSquareCircle,
    this.shareRedirectLink = StreamIconData.iconShareRedirectLink,
    this.shield = StreamIconData.iconShield,
    this.squareBehindSquare2Copy = StreamIconData.iconSquareBehindSquare2Copy,
    this.squareCircleTopRightFeeds = StreamIconData.iconSquareCircleTopRightFeeds,
    this.stop = StreamIconData.iconStop,
    this.table = StreamIconData.iconTable,
    this.team = StreamIconData.iconTeam,
    this.tennis = StreamIconData.iconTennis,
    this.textToImageURLEnrichment = StreamIconData.iconTextToImageURLEnrichment,
    this.thunder = StreamIconData.iconThunder,
    this.trashBin = StreamIconData.iconTrashBin,
    this.trending4 = StreamIconData.iconTrending4,
    this.unlocked = StreamIconData.iconUnlocked,
    this.users = StreamIconData.iconUsers,
    this.video = StreamIconData.iconVideo,
    this.videoSolid = StreamIconData.iconVideoSolid,
    this.voiceAndVideo = StreamIconData.iconVoiceAndVideo,
    this.voiceHigh = StreamIconData.iconVoiceHigh,
    this.volumeFull = StreamIconData.iconVolumeFull,
    this.webhook = StreamIconData.iconWebhook,
  });

  /// The api aggregate icon.
  final IconData apiAggregate;

  /// The apples icon.
  final IconData apples;

  /// The arrow box left icon.
  final IconData arrowBoxLeft;

  /// The arrow down icon.
  final IconData arrowDown;

  /// The arrow left icon.
  final IconData arrowLeft;

  /// The arrow right icon.
  final IconData arrowRight;

  /// The arrow rotate clockwise icon.
  final IconData arrowRotateClockwise;

  /// The arrow rotate right left repeat refresh icon.
  final IconData arrowRotateRightLeftRepeatRefresh;

  /// The arrow share left icon.
  final IconData arrowShareLeft;

  /// The arrow up icon.
  final IconData arrowUp;

  /// The arrows repeat left right icon.
  final IconData arrowsRepeatLeftRight;

  /// The at icon.
  final IconData at;

  /// The at solid icon.
  final IconData atSolid;

  /// The bell notification icon.
  final IconData bellNotification;

  /// The browser a i sparkle icon.
  final IconData browserAISparkle;

  /// The bubble3 chat message icon.
  final IconData bubble3ChatMessage;

  /// The bubble3 solid icon.
  final IconData bubble3Solid;

  /// The bubble annotation2 chat message icon.
  final IconData bubbleAnnotation2ChatMessage;

  /// The bubble text6 chat message icon.
  final IconData bubbleText6ChatMessage;

  /// The bubble text6 solid icon.
  final IconData bubbleText6Solid;

  /// The bubble wide notification chat message icon.
  final IconData bubbleWideNotificationChatMessage;

  /// The bubble wide sparkle chat message icon.
  final IconData bubbleWideSparkleChatMessage;

  /// The calendar1 icon.
  final IconData calendar1;

  /// The call cancel icon.
  final IconData callCancel;

  /// The camera1 icon.
  final IconData camera1;

  /// The car1 icon.
  final IconData car1;

  /// The cat icon.
  final IconData cat;

  /// The chain link3 icon.
  final IconData chainLink3;

  /// The chart5 icon.
  final IconData chart5;

  /// The checkmark1 small icon.
  final IconData checkmark1Small;

  /// The checkmark2 icon.
  final IconData checkmark2;

  /// The checkmark2 small icon.
  final IconData checkmark2Small;

  /// The chevron down icon.
  final IconData chevronDown;

  /// The chevron grabber vertical selector icon.
  final IconData chevronGrabberVerticalSelector;

  /// The chevron left icon.
  final IconData chevronLeft;

  /// The chevron right icon.
  final IconData chevronRight;

  /// The chevron top icon.
  final IconData chevronTop;

  /// The circle ban sign icon.
  final IconData circleBanSign;

  /// The circle check icon.
  final IconData circleCheck;

  /// The circle info tooltip icon.
  final IconData circleInfoTooltip;

  /// The circle minus icon.
  final IconData circleMinus;

  /// The circle questionmark icon.
  final IconData circleQuestionmark;

  /// The circle questionmark filled icon.
  final IconData circleQuestionmarkFilled;

  /// The circle x icon.
  final IconData circleX;

  /// The clock icon.
  final IconData clock;

  /// The clock solid icon.
  final IconData clockSolid;

  /// The code icon.
  final IconData code;

  /// The code brackets icon.
  final IconData codeBrackets;

  /// The code editor insert icon.
  final IconData codeEditorInsert;

  /// The compass icon.
  final IconData compass;

  /// The credit card2 billing icon.
  final IconData creditCard2Billing;

  /// The cross medium icon.
  final IconData crossMedium;

  /// The cross small icon.
  final IconData crossSmall;

  /// The dot grid2x3 icon.
  final IconData dotGrid2x3;

  /// The dots grid1x3 vertical icon.
  final IconData dotsGrid1x3Vertical;

  /// The douple checkmark1 small icon.
  final IconData doupleCheckmark1Small;

  /// The edit big icon.
  final IconData editBig;

  /// The edit big solid icon.
  final IconData editBigSolid;

  /// The emoji add reaction icon.
  final IconData emojiAddReaction;

  /// The emoji smile icon.
  final IconData emojiSmile;

  /// The exclamation circle icon.
  final IconData exclamationCircle;

  /// The exclamation circle1 icon.
  final IconData exclamationCircle1;

  /// The exclamation triangle icon.
  final IconData exclamationTriangle;

  /// The exclamation triangle1 icon.
  final IconData exclamationTriangle1;

  /// The eye open icon.
  final IconData eyeOpen;

  /// The file bend icon.
  final IconData fileBend;

  /// The filled circle info tooltip icon.
  final IconData filledCircleInfoTooltip;

  /// The filter1 icon.
  final IconData filter1;

  /// The flag2 icon.
  final IconData flag2;

  /// The gauge icon.
  final IconData gauge;

  /// The google icon.
  final IconData google;

  /// The hashtag channel icon.
  final IconData hashtagChannel;

  /// The heart2 icon.
  final IconData heart2;

  /// The history icon.
  final IconData history;

  /// The images1 alt icon.
  final IconData images1Alt;

  /// The invite icon.
  final IconData invite;

  /// The layers behind icon.
  final IconData layersBehind;

  /// The layout grid1 icon.
  final IconData layoutGrid1;

  /// The light bulb simple icon.
  final IconData lightBulbSimple;

  /// The limits icon.
  final IconData limits;

  /// The line chart3 icon.
  final IconData lineChart3;

  /// The lock icon.
  final IconData lock;

  /// The magnifying glass search icon.
  final IconData magnifyingGlassSearch;

  /// The map pin icon.
  final IconData mapPin;

  /// The microphone icon.
  final IconData microphone;

  /// The microphone solid icon.
  final IconData microphoneSolid;

  /// The minus large icon.
  final IconData minusLarge;

  /// The minus small icon.
  final IconData minusSmall;

  /// The mute icon.
  final IconData mute;

  /// The newspaper2 icon.
  final IconData newspaper2;

  /// The organization icon.
  final IconData organization;

  /// The paper plane icon.
  final IconData paperPlane;

  /// The paper plane top right icon.
  final IconData paperPlaneTopRight;

  /// The paperclip1 icon.
  final IconData paperclip1;

  /// The paragraphs text icon.
  final IconData paragraphsText;

  /// The pause icon.
  final IconData pause;

  /// The pencil icon.
  final IconData pencil;

  /// The people icon.
  final IconData people;

  /// The people2 icon.
  final IconData people2;

  /// The people add icon.
  final IconData peopleAdd;

  /// The people added icon.
  final IconData peopleAdded;

  /// The people circle icon.
  final IconData peopleCircle;

  /// The people copy icon.
  final IconData peopleCopy;

  /// The people edit user rights icon.
  final IconData peopleEditUserRights;

  /// The people remove icon.
  final IconData peopleRemove;

  /// The persona icon.
  final IconData persona;

  /// The pin icon.
  final IconData pin;

  /// The play solid icon.
  final IconData playSolid;

  /// The plus large icon.
  final IconData plusLarge;

  /// The plus small icon.
  final IconData plusSmall;

  /// The run shortcut icon.
  final IconData runShortcut;

  /// The search text icon.
  final IconData searchText;

  /// The settings gear2 icon.
  final IconData settingsGear2;

  /// The settings slider ver icon.
  final IconData settingsSliderVer;

  /// The shapes plus close square circle icon.
  final IconData shapesPlusCloseSquareCircle;

  /// The shapes triangle square circle icon.
  final IconData shapesTriangleSquareCircle;

  /// The share redirect link icon.
  final IconData shareRedirectLink;

  /// The shield icon.
  final IconData shield;

  /// The square behind square2 copy icon.
  final IconData squareBehindSquare2Copy;

  /// The square circle top right feeds icon.
  final IconData squareCircleTopRightFeeds;

  /// The stop icon.
  final IconData stop;

  /// The table icon.
  final IconData table;

  /// The team icon.
  final IconData team;

  /// The tennis icon.
  final IconData tennis;

  /// The text to image u r l enrichment icon.
  final IconData textToImageURLEnrichment;

  /// The thunder icon.
  final IconData thunder;

  /// The trash bin icon.
  final IconData trashBin;

  /// The trending4 icon.
  final IconData trending4;

  /// The unlocked icon.
  final IconData unlocked;

  /// The users icon.
  final IconData users;

  /// The video icon.
  final IconData video;

  /// The video solid icon.
  final IconData videoSolid;

  /// The voice and video icon.
  final IconData voiceAndVideo;

  /// The voice high icon.
  final IconData voiceHigh;

  /// The volume full icon.
  final IconData volumeFull;

  /// The webhook icon.
  final IconData webhook;

  /// A map of all available icons keyed by their field name.
  ///
  /// Useful for dynamic icon lookup by string name.
  ///
  /// ```dart
  /// final icon = context.streamIcons.allIcons['settingsGear2'];
  /// ```
  Map<String, IconData> get allIcons => {
    'apiAggregate': apiAggregate,
    'apples': apples,
    'arrowBoxLeft': arrowBoxLeft,
    'arrowDown': arrowDown,
    'arrowLeft': arrowLeft,
    'arrowRight': arrowRight,
    'arrowRotateClockwise': arrowRotateClockwise,
    'arrowRotateRightLeftRepeatRefresh': arrowRotateRightLeftRepeatRefresh,
    'arrowShareLeft': arrowShareLeft,
    'arrowUp': arrowUp,
    'arrowsRepeatLeftRight': arrowsRepeatLeftRight,
    'at': at,
    'atSolid': atSolid,
    'bellNotification': bellNotification,
    'browserAISparkle': browserAISparkle,
    'bubble3ChatMessage': bubble3ChatMessage,
    'bubble3Solid': bubble3Solid,
    'bubbleAnnotation2ChatMessage': bubbleAnnotation2ChatMessage,
    'bubbleText6ChatMessage': bubbleText6ChatMessage,
    'bubbleText6Solid': bubbleText6Solid,
    'bubbleWideNotificationChatMessage': bubbleWideNotificationChatMessage,
    'bubbleWideSparkleChatMessage': bubbleWideSparkleChatMessage,
    'calendar1': calendar1,
    'callCancel': callCancel,
    'camera1': camera1,
    'car1': car1,
    'cat': cat,
    'chainLink3': chainLink3,
    'chart5': chart5,
    'checkmark1Small': checkmark1Small,
    'checkmark2': checkmark2,
    'checkmark2Small': checkmark2Small,
    'chevronDown': chevronDown,
    'chevronGrabberVerticalSelector': chevronGrabberVerticalSelector,
    'chevronLeft': chevronLeft,
    'chevronRight': chevronRight,
    'chevronTop': chevronTop,
    'circleBanSign': circleBanSign,
    'circleCheck': circleCheck,
    'circleInfoTooltip': circleInfoTooltip,
    'circleMinus': circleMinus,
    'circleQuestionmark': circleQuestionmark,
    'circleQuestionmarkFilled': circleQuestionmarkFilled,
    'circleX': circleX,
    'clock': clock,
    'clockSolid': clockSolid,
    'code': code,
    'codeBrackets': codeBrackets,
    'codeEditorInsert': codeEditorInsert,
    'compass': compass,
    'creditCard2Billing': creditCard2Billing,
    'crossMedium': crossMedium,
    'crossSmall': crossSmall,
    'dotGrid2x3': dotGrid2x3,
    'dotsGrid1x3Vertical': dotsGrid1x3Vertical,
    'doupleCheckmark1Small': doupleCheckmark1Small,
    'editBig': editBig,
    'editBigSolid': editBigSolid,
    'emojiAddReaction': emojiAddReaction,
    'emojiSmile': emojiSmile,
    'exclamationCircle': exclamationCircle,
    'exclamationCircle1': exclamationCircle1,
    'exclamationTriangle': exclamationTriangle,
    'exclamationTriangle1': exclamationTriangle1,
    'eyeOpen': eyeOpen,
    'fileBend': fileBend,
    'filledCircleInfoTooltip': filledCircleInfoTooltip,
    'filter1': filter1,
    'flag2': flag2,
    'gauge': gauge,
    'google': google,
    'hashtagChannel': hashtagChannel,
    'heart2': heart2,
    'history': history,
    'images1Alt': images1Alt,
    'invite': invite,
    'layersBehind': layersBehind,
    'layoutGrid1': layoutGrid1,
    'lightBulbSimple': lightBulbSimple,
    'limits': limits,
    'lineChart3': lineChart3,
    'lock': lock,
    'magnifyingGlassSearch': magnifyingGlassSearch,
    'mapPin': mapPin,
    'microphone': microphone,
    'microphoneSolid': microphoneSolid,
    'minusLarge': minusLarge,
    'minusSmall': minusSmall,
    'mute': mute,
    'newspaper2': newspaper2,
    'organization': organization,
    'paperPlane': paperPlane,
    'paperPlaneTopRight': paperPlaneTopRight,
    'paperclip1': paperclip1,
    'paragraphsText': paragraphsText,
    'pause': pause,
    'pencil': pencil,
    'people': people,
    'people2': people2,
    'peopleAdd': peopleAdd,
    'peopleAdded': peopleAdded,
    'peopleCircle': peopleCircle,
    'peopleCopy': peopleCopy,
    'peopleEditUserRights': peopleEditUserRights,
    'peopleRemove': peopleRemove,
    'persona': persona,
    'pin': pin,
    'playSolid': playSolid,
    'plusLarge': plusLarge,
    'plusSmall': plusSmall,
    'runShortcut': runShortcut,
    'searchText': searchText,
    'settingsGear2': settingsGear2,
    'settingsSliderVer': settingsSliderVer,
    'shapesPlusCloseSquareCircle': shapesPlusCloseSquareCircle,
    'shapesTriangleSquareCircle': shapesTriangleSquareCircle,
    'shareRedirectLink': shareRedirectLink,
    'shield': shield,
    'squareBehindSquare2Copy': squareBehindSquare2Copy,
    'squareCircleTopRightFeeds': squareCircleTopRightFeeds,
    'stop': stop,
    'table': table,
    'team': team,
    'tennis': tennis,
    'textToImageURLEnrichment': textToImageURLEnrichment,
    'thunder': thunder,
    'trashBin': trashBin,
    'trending4': trending4,
    'unlocked': unlocked,
    'users': users,
    'video': video,
    'videoSolid': videoSolid,
    'voiceAndVideo': voiceAndVideo,
    'voiceHigh': voiceHigh,
    'volumeFull': volumeFull,
    'webhook': webhook,
  };

  /// Linearly interpolate between two [StreamIcons] objects.
  static StreamIcons? lerp(
    StreamIcons? a,
    StreamIcons? b,
    double t,
  ) => _$StreamIcons.lerp(a, b, t);
}
