// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace stream_thumbnail_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class StreamThumbnailHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Wire representation of the image format for a generated thumbnail.
enum class ThumbnailFormat {
  kJpeg = 0,
  kPng = 1,
  kWebp = 2
};


// A single thumbnail generation request sent to the native platform.
//
// Generated class from Pigeon that represents data sent in messages.
class ThumbnailRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ThumbnailRequest(
    const std::string& video,
    const ThumbnailFormat& format,
    int64_t max_height,
    int64_t max_width,
    int64_t time_ms,
    int64_t quality);

  // Constructs an object setting all fields.
  explicit ThumbnailRequest(
    const std::string& video,
    const ::flutter::EncodableMap* headers,
    const std::string* thumbnail_path,
    const ThumbnailFormat& format,
    int64_t max_height,
    int64_t max_width,
    int64_t time_ms,
    int64_t quality);

  const std::string& video() const;
  void set_video(std::string_view value_arg);

  const ::flutter::EncodableMap* headers() const;
  void set_headers(const ::flutter::EncodableMap* value_arg);
  void set_headers(const ::flutter::EncodableMap& value_arg);

  const std::string* thumbnail_path() const;
  void set_thumbnail_path(const std::string_view* value_arg);
  void set_thumbnail_path(std::string_view value_arg);

  const ThumbnailFormat& format() const;
  void set_format(const ThumbnailFormat& value_arg);

  int64_t max_height() const;
  void set_max_height(int64_t value_arg);

  int64_t max_width() const;
  void set_max_width(int64_t value_arg);

  int64_t time_ms() const;
  void set_time_ms(int64_t value_arg);

  int64_t quality() const;
  void set_quality(int64_t value_arg);

  bool operator==(const ThumbnailRequest& other) const;
  bool operator!=(const ThumbnailRequest& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ThumbnailRequest& obj);
 private:
  static ThumbnailRequest FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class StreamThumbnailHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string video_;
  std::optional<::flutter::EncodableMap> headers_;
  std::optional<std::string> thumbnail_path_;
  ThumbnailFormat format_;
  int64_t max_height_;
  int64_t max_width_;
  int64_t time_ms_;
  int64_t quality_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class StreamThumbnailHostApi {
 public:
  StreamThumbnailHostApi(const StreamThumbnailHostApi&) = delete;
  StreamThumbnailHostApi& operator=(const StreamThumbnailHostApi&) = delete;
  virtual ~StreamThumbnailHostApi() {}
  // Generates a thumbnail for [ThumbnailRequest.video] and returns its bytes.
  virtual void ThumbnailData(
    const ThumbnailRequest& request,
    std::function<void(ErrorOr<std::vector<uint8_t>> reply)> result) = 0;
  // Generates a thumbnail for [ThumbnailRequest.video] and returns the path
  // it was written to.
  virtual void ThumbnailFile(
    const ThumbnailRequest& request,
    std::function<void(ErrorOr<std::string> reply)> result) = 0;

  // The codec used by StreamThumbnailHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `StreamThumbnailHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    StreamThumbnailHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    StreamThumbnailHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  StreamThumbnailHostApi() = default;
};
}  // namespace stream_thumbnail_windows
#endif  // PIGEON_MESSAGES_G_H_
