name: stream_thumbnail_example
description: "An example app for the stream_thumbnail plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  stream_thumbnail: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
