// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Wire representation of the image format for a generated thumbnail.
enum ThumbnailFormat {
  jpeg,
  png,
  webp,
}

/// A single thumbnail generation request sent to the native platform.
class ThumbnailRequest {
  ThumbnailRequest({
    required this.video,
    this.headers,
    this.thumbnailPath,
    required this.format,
    required this.maxHeight,
    required this.maxWidth,
    required this.timeMs,
    required this.quality,
  });

  String video;

  Map<String, String>? headers;

  String? thumbnailPath;

  ThumbnailFormat format;

  int maxHeight;

  int maxWidth;

  int timeMs;

  int quality;

  List<Object?> _toList() {
    return <Object?>[
      video,
      headers,
      thumbnailPath,
      format,
      maxHeight,
      maxWidth,
      timeMs,
      quality,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ThumbnailRequest decode(Object result) {
    result as List<Object?>;
    return ThumbnailRequest(
      video: result[0]! as String,
      headers: (result[1] as Map<Object?, Object?>?)?.cast<String, String>(),
      thumbnailPath: result[2] as String?,
      format: result[3]! as ThumbnailFormat,
      maxHeight: result[4]! as int,
      maxWidth: result[5]! as int,
      timeMs: result[6]! as int,
      quality: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThumbnailRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(video, other.video) &&
        _deepEquals(headers, other.headers) &&
        _deepEquals(thumbnailPath, other.thumbnailPath) &&
        _deepEquals(format, other.format) &&
        _deepEquals(maxHeight, other.maxHeight) &&
        _deepEquals(maxWidth, other.maxWidth) &&
        _deepEquals(timeMs, other.timeMs) &&
        _deepEquals(quality, other.quality);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ThumbnailRequest(video: $video, headers: $headers, thumbnailPath: $thumbnailPath, format: $format, maxHeight: $maxHeight, maxWidth: $maxWidth, timeMs: $timeMs, quality: $quality)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ThumbnailFormat) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ThumbnailRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ThumbnailFormat.values[value];
      case 130:
        return ThumbnailRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class StreamThumbnailHostApi {
  /// Constructor for [StreamThumbnailHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StreamThumbnailHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generates a thumbnail for [ThumbnailRequest.video] and returns its bytes.
  Future<Uint8List> thumbnailData(ThumbnailRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stream_thumbnail.StreamThumbnailHostApi.thumbnailData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Generates a thumbnail for [ThumbnailRequest.video] and returns the path
  /// it was written to.
  Future<String> thumbnailFile(ThumbnailRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stream_thumbnail.StreamThumbnailHostApi.thumbnailFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }
}
