name: stream_core_flutter
description: "Stream Design System for Flutter and cross-SDK utilities that depend on Flutter."
version: 0.1.0
homepage: https://github.com/GetStream/stream-core-flutter

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  cached_network_image_ce: ^4.6.3
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  flutter_svg: ^2.2.3
  markdown: ^7.3.0
  shimmer: ^3.0.0
  stream_core: ^0.4.0
  svg_icon_widget: ^0.0.1+1
  theme_extensions_builder_annotation: ^7.1.0

dev_dependencies:
  alchemist: ^0.13.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  theme_extensions_builder: ^7.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/file_type/
    - assets/icons/

  fonts:
    - family: Stream Icons
      fonts:
        - asset: packages/stream_core_flutter/fonts/stream_icons_font.otf

